version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_url_shortener
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: url_shortener
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  adminer:
    image: adminer
    container_name: adminer_url_shortener
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
